FROM golang:1.9

RUN apt-get update
RUN apt-get install --yes curl git make


RUN go get github.com/golang/dep/...

RUN mkdir -p $GOPATH/src/github.com/andrepinto/helmsman

VOLUME  /go/src/github.com/andrepinto/helmsman/bin

COPY . $GOPATH/src/github.com/andrepinto/helmsman

WORKDIR $GOPATH/src/github.com/andrepinto/helmsman

RUN make dep
RUN make
